Verify whether automatic key rotation is enabled only for symmetric keys
Since the GCP Key Management Service does not support automatic rotation
of asymmetric keys (see: [Considerations for asymmetric
keys](https://cloud.google.com/kms/docs/key-rotation#asymmetric)),
checks running against such keys are failing at the moment. That's why
we should only test KMS cryptographic keys which are symmetric.

Fixes error:
```
     ×  Control Source Code Error inspec-gcp-cis-benchmark-1.1.0-9/controls/1.10-iam.rb:24
          undefined method `[]' for nil:NilClass
```